### ISSUE TITLE
Wording and problems in Theory.ipynb notebook

### ISSUE THREAD

**Issue by ncclementi** [bjmorgan/pyscses#7]
1. I was reading the notebook and I landed on the paragraph below that is hard to understand since the word "boundary" appears four times, is there a way to rephrase this? 

"For solid electrolytes, the Poisson-Boltzmann equation is commonly solved by treating the grain **boundary** via the **boundary** condition by setting the grain **boundary** potential. However the grain **boundary** can be treated explicitly..."

2. For the record, every time you use "However"  at the beginning of a sentence you need to put a comma afterwards. (I caught some and submit a PR same with typos, but I might have missed some). For the misspelled words, I's suggest you install a spell checker for jupyter notebooks, there are many options out there.  

3. The image `<img src="Figures/irregulargrid.png">`  doesn't exists and therefore doesn't render.

**Comment by georgiewellock** [comment]
I have reworded the paragraph to avoid using 'boundary' so frequently. I have imported used a spell checker and corrected the mistakes flagged up and I have fixed the irregular grid figure so that it renders in the notebook. These changes can be found in commit https://github.com/bjmorgan/pyscses/commit/2c2965e360f5479e5a8e0b9eb4d717482916e8bf.

**Comment by ncclementi** [comment]
@georgiewellock I still can't render the image, it seems it's not on the repository because it can't find it. Maybe you have it locally but it's not in the repo, can you please push the image?  
Thanks

**Comment by georgiewellock** [comment]
Yes, sorry I forgot to push up the new image. I have done so now: https://github.com/bjmorgan/pyscses/commit/7dba222392bfcbc750fc6cba6a13789ab29bc18e

**Comment by ncclementi** [comment]
Thanks, I think you cover everything on this issue so feel free to close it. 
Great job!
